### PR TITLE
recursive readme was too recursive

### PR DESCRIPTION
**Pull request by davharris**
fixed typo; dbplyr is not its own backend.

### CODE REVIEW

**Comment by naupaka** [comment]
I was wondering about that too. Seems like Travis prefers recursion, though.

**Comment by davharris** [comment]
I think this is the reason behind the failure?

>  Warning: Installed R (R Under development (unstable) (2017-03-30 r72444)) different from R used to build dplyr (R Under development (unstable) (2017-03-30 r72439)).

Either that or maybe Travis really does prefer the recursive name that Travis prefers.

**Comment by hadley** [comment]
We did some crazy history rewriting so was easier to fix by hand. Thanks!

**Comment by davharris** [comment]
Yeah... merging after the histories diverged by 250+ commits would _probably_ be a bad idea.

**Pull request closed without merging**
